# Generated by Django 2.1.2 on 2019-05-24 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groceryApp', '0002_grocerylist_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grocerylist', to=settings.AUTH_USER_MODEL),
        ),
    ]
